"""Pydantic v2 schemas for the Enterprise Nested LangGraph system.

These schemas are the canonical data contracts used across the
supervisor graph and its subgraphs. They are intentionally distinct
from the LangGraph state object (``models.state.GraphState``) so that
Pydantic models can be validated, serialized, and reused independently
of the graph runtime.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Severity(str, Enum):
    """Severity levels for guardrail violations and errors."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ResearchTask(BaseModel):
    """A single research task generated by the planner."""

    model_config = ConfigDict(frozen=False, extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid4()))
    objective: str = Field(..., min_length=1, max_length=500)
    rationale: str = Field(default="", max_length=1000)
    priority: int = Field(default=1, ge=1, le=5)
    dependencies: list[str] = Field(default_factory=list)

    @field_validator("objective")
    @classmethod
    def _strip_objective(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("objective must not be empty after stripping")
        return cleaned


class ResearchFinding(BaseModel):
    """A single research finding produced by the executor."""

    model_config = ConfigDict(extra="forbid")

    task_id: str
    title: str = Field(..., min_length=1, max_length=300)
    summary: str = Field(..., min_length=1)
    source: str = Field(default="internal")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(tz=timezone.utc))


class AnalyticsMetric(BaseModel):
    """A single computed analytics metric."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(..., min_length=1, max_length=120)
    value: float
    unit: str = Field(default="")
    trend: str = Field(default="flat")
    period: str = Field(default="current")
    notes: str = Field(default="", max_length=500)


class AnalyticsResult(BaseModel):
    """Result of an analytics subgraph execution."""

    model_config = ConfigDict(extra="forbid")

    kpis: list[AnalyticsMetric] = Field(default_factory=list)
    aggregations: dict[str, float] = Field(default_factory=dict)
    sql_queries_executed: int = Field(default=0, ge=0)
    calculations_performed: int = Field(default=0, ge=0)
    notes: str = Field(default="", max_length=2000)


class ReportSection(BaseModel):
    """A single section in the final report."""

    model_config = ConfigDict(extra="forbid")

    heading: str = Field(..., min_length=1, max_length=200)
    body: str = Field(..., min_length=1)
    order: int = Field(default=0, ge=0)


class ReportReview(BaseModel):
    """Outcome of the reporting reviewer."""

    model_config = ConfigDict(extra="forbid")

    approved: bool
    completeness_score: float = Field(ge=0.0, le=1.0)
    formatting_score: float = Field(ge=0.0, le=1.0)
    consistency_score: float = Field(ge=0.0, le=1.0)
    feedback: str = Field(default="", max_length=2000)
    pass_number: int = Field(default=1, ge=1)


class GuardrailViolation(BaseModel):
    """A single guardrail violation."""

    model_config = ConfigDict(extra="forbid")

    category: str = Field(..., min_length=1, max_length=100)
    pattern: str = Field(..., min_length=1, max_length=200)
    severity: Severity = Severity.MEDIUM
    description: str = Field(default="")


class SubgraphTiming(BaseModel):
    """Timing information for a single subgraph execution."""

    model_config = ConfigDict(extra="forbid")

    name: str
    started_at: datetime
    finished_at: datetime
    duration_ms: float

    @classmethod
    def from_times(cls, name: str, started: datetime, finished: datetime) -> SubgraphTiming:
        duration = (finished - started).total_seconds() * 1000.0
        return cls(name=name, started_at=started, finished_at=finished, duration_ms=duration)


def metadata_factory() -> dict[str, Any]:
    """Default factory for the ``metadata`` field."""
    return {
        "subgraph_timings": [],
        "state_transitions": [],
        "guardrail_violations": [],
    }


__all__ = [
    "AnalyticsMetric",
    "AnalyticsResult",
    "GuardrailViolation",
    "ReportReview",
    "ReportSection",
    "ResearchFinding",
    "ResearchTask",
    "Severity",
    "SubgraphTiming",
    "metadata_factory",
]
